In [1]:
import cv2
import numpy as np

In [2]:
img=cv2.imread(r"C:\Users\obunn\OneDrive\Pictures\desktop-367124.jpg")

In [3]:
cv2.imshow("original",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
width = 800
aspect_ratio = img.shape[1] / img.shape[0] 
height = int(width / aspect_ratio)
image = cv2.resize(img, (width, height))
cv2.imshow("Resized", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
b,g,r=cv2.split(image)
cv2.imshow("blue",b)
cv2.imshow("green",g)
cv2.imshow("red",r)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
gray_image=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray", gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
matrix=np.array(b)
b_t=matrix.T
print(b_t)
print(b)

[[ 78  79  80 ...  66 115 112]
 [ 76  76  78 ...  80  98 134]
 [ 73  76  80 ...  89  90 149]
 ...
 [ 15   5  16 ...  62  79  65]
 [ 45  50  47 ...  67  98 107]
 [ 55  43  54 ...  94  82 114]]
[[ 78  76  73 ...  15  45  55]
 [ 79  76  76 ...   5  50  43]
 [ 80  78  80 ...  16  47  54]
 ...
 [ 66  80  89 ...  62  67  94]
 [115  98  90 ...  79  98  82]
 [112 134 149 ...  65 107 114]]


In [12]:
cv2.imshow("blue",b)
cv2.imshow("bluw_t",b_t)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
src=cv2.imread(r"C:\Users\obunn\OneDrive\Documents\exp_2.jpg")
cv2.imshow("Enhanced", src/0.5)
cv2.waitKey(0)
cv2.destroyAllWindows()